pipeline {

  agent any

  tools {
    maven "MAVEN3"
    jdk "OracleJDK17"
  }

  environment {
    registry = "alfianyaqien/vproapp"
    registryCredential = 'dockerhub'
  }

  stages {
    stage('Build') {
      steps {
        sh 'mvn clean install -DskipTests'
      }
      post {
        success {
          echo 'Now Archiving...'
          archiveArtifacts artifacts: '*.jar'
        }
      }
    }

    stage('Unit Test') {
      steps {
        sh 'mvn test'
      }
    }

    stage('Integration Test') {
      steps {
        sh 'mvn verify -DskipUnitTests'
      }
    }

    stage('Code Analysis') {
      steps {
        sh 'mvn checkstyle:checkstyle'
      }
      post {
        success {
          echo 'Generated Analysis Result'
        }
      }
    }

    stage('Build App Image') {
      steps {
        script {
          dockerImage = docker.build registry + ":V$BUILD_NUMBER"
        }
      }
    }

    stage('Upload Image') {
      steps {
        script {
          docker.withRegistry('', registryCredential) {
            dockerImage.push("V$BUILD_NUMBER")
            dockerImage.push('latest')
          }
        }
      }
    }

    stage('Remove Unused Docker Image') {
      steps {
        sh "docker rmi $registry:V$BUILD_NUMBER"
      }
    }

    stage('Kubernetes Deploy') {
      agent {label 'KOPS'}
      steps {
        sh "helm upgrade --install --force retail-app-ui kubernetes/charts/ui --set appimage=${registry}:V${BUILD_NUMBER} --namespace prod"
      }
    }
  }
}